# See config.example.yml for documentation.
name: wii-vc
object: orig/sm64-e/content1.app
hash: 4d65a6aabcc9d902df6a84ad53e3c7619a85b4fb
symbols: config/sm64-e/symbols.txt
splits: config/sm64-e/splits.txt

# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 14

extract:
# DSPCode.c
- symbol: axDspSlave
  header: axDspSlave.inc
# AXComp.c
- symbol: __AXCompressorTable
  header: __AXCompressorTable.inc

force_active:
- lbl_801E3380
- DemoAllocator2
- TRKAccessFile
- TRKOpenFile
- TRKCloseFile
- TRKPositionFile
- sSetInfoAsync__Q210homebutton10Controller
- lbl_8025DBBC__Q210homebutton10Controller

add_relocations:
- source: 0x8005D0B0
  type: ha
  target: GenPerspective_1080
- source: 0x8005D0D8
  type: l
  target: GenPerspective_1080

block_relocations:
# system.c
- source: 0x8000B16C
- source: 0x8000B17C
- source: 0x8000B198
- source: 0x8000B1A0
- source: 0x8000B1C4
- source: 0x8000B1E8
- source: 0x8000B210
- source: 0x8000B220
- source: 0x8000B23C
- source: 0x8000B244
- source: 0x8000B268
- source: 0x8000B28C
- source: 0x8000B2B8
- source: 0x8000B2C8
- source: 0x8000B2E4
- source: 0x8000B2EC
- source: 0x8000B314
- source: 0x8000B338
- source: 0x8000B678
- source: 0x8000B680
- source: 0x8000B6A8
- source: 0x8000B6B0
- source: 0x8000B6D0
- source: 0x8000B6D8
- source: 0x8000B7F4
- source: 0x8000B7FC
- source: 0x8000B86C
- source: 0x8000B87C
- source: 0x8000B898
- source: 0x8000B8A8
- source: 0x8000B8C8
- source: 0x8000B8E0
- source: 0x8000B908
- source: 0x8000B918
- source: 0x8000B938
- source: 0x8000B9C4
- source: 0x8000B9CC
- source: 0x8000B9F0
- source: 0x8000BA14
- source: 0x8000BA38
- source: 0x8000BA40
- source: 0x8000BA64
- source: 0x8000BA88
- source: 0x8000BAD8
- source: 0x8000BAF0
- source: 0x8000BB20
- source: 0x8000BB48
- source: 0x8000BB68
- source: 0x8000BB78
- source: 0x8000BB98
- source: 0x8000BBC4
- source: 0x8000B640
- source: 0x8000B648
- source: 0x8000B7C4
- source: 0x8000B7CC
- source: 0x8000BBE8
- source: 0x8000BC00
- source: 0x8000BC2C
- source: 0x8000BC4C
- source: 0x8000BC5C
- source: 0x8000BC98
- source: 0x8000BCA8
- source: 0x8000BCCC
- source: 0x8000BD8C
- source: 0x8000BD9C
- source: 0x8000BDC0
- source: 0x8000BDE8
- source: 0x8000BE0C
- source: 0x8000BE38
- source: 0x8000BE54
- source: 0x8000BE64
- source: 0x8000BEC0
- source: 0x8000BED0
- source: 0x8000BEEC
- source: 0x8000BF0C
- source: 0x8000BF1C
- source: 0x8000BF3C
- source: 0x8000C010
- source: 0x8000C020
- source: 0x8000C058
- source: 0x8000C070
- source: 0x8000C0A8
- source: 0x8000C0B0
- source: 0x8000C0D0
- source: 0x8000C0E0
- source: 0x8000C104
- source: 0x8000C1BC
- source: 0x8000C1CC
