compiler_type = "mwcc"
compiler_command = "wibo tools/mwcc_compiler/GC/3.0a5/mwcceppc.exe -Cpp_exceptions off -proc gekko -fp hardware -fp_contract on -enum int -align powerpc -nosyspath -RTTI off -str reuse -multibyte -O4,p -inline auto,deferred -nodefaults -msgstyle gcc -Iinclude -Ilibc -Ibuild/oot-j/include -c"
assembler_command = "tools/binutils/powerpc-eabi-as -mgekko"
asm_prelude_file = "include/macros.inc"

[preserve_macros]
"NULL" = "void*"
"true" = "int"
"false" = "int"
"ALIGN_PREV" = "int"
"ALIGN_NEXT" = "int"
"ARRAY_COUNT" = "int"
"ARRAY_COUNTU" = "unsigned int"
"OFFSETOF" = "int"
