name: Build

on:
  push:
  pull_request:

jobs:
  build:
    container: ghcr.io/zeldaret/oot-gc-vc-build:main
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        matching: [true, false]
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository (shallow clone)
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    # Set Git config
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    # Copy the original files to the workspace
    - name: Prepare
      run: cp -R /orig .

    # Build the project
    - name: Build
      if: matrix.matching
      run: |
        python configure.py --map --binutils /binutils --compilers /compilers
        ninja all_source build/{oot-j}/progress.json build/report.json

    # Build the project (non-matching)
    - name: Build (non-matching)
      if: ${{ !matrix.matching }}
      run: |
        python configure.py --map --binutils /binutils --compilers /compilers --non-matching --no-asm-processor
        ninja all_source build/{oot-j}/progress.json build/report.json

    # Upload progress if we're on the main branch
    - name: Upload progress
      if: ${{ !matrix.matching && github.ref == 'refs/heads/main' }}
      continue-on-error: true
      env:
        PROGRESS_SLUG: oot-vc
        PROGRESS_API_KEY: ${{ secrets.PROGRESS_API_KEY }}
      run: |
        for version in {oot-j}; do
          python tools/upload_progress.py -b https://progress.decomp.club/ \
            -p $PROGRESS_SLUG -v $version build/$version/progress.json
        done

    # Upload map files
    - name: Upload map
      if: matrix.matching
      uses: actions/upload-artifact@v4
      with:
        name: combined_maps
        path: build/**/*.MAP

    # Upload progress report
    - name: Upload report
      if: ${{ !matrix.matching }}
      uses: actions/upload-artifact@v4
      with:
        name: combined_report
        path: build/report.json
